name: Check Description on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  description-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check Description Length
        uses: Tony-Katz/enforce-pr-description-length-action@v1
        with:
          minLength: 3 # Установите желаемую минимальную длину описания

      - name: End Pipeline on Invalid Description
        if: failure()
        run: exit 1

