name: Проверка Description в Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_description:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка Description
      id: check_description
      run: |
        pr_description=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        if [ -n "$pr_description" ]; then
          echo "Поле Description в пулл-реквесте заполнено."
        fi
