name: html css linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: install package
      run: npm install

    - name: html lint
      run: npx htmlhint "**/*.html"

    - name: css lint
      run: |
        npm install -g csslint
        csslint "css/style.css"
